# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=255)),
                ('a_info', models.CharField(max_length=300)),
                ('a_content', models.TextField()),
                ('a_img', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('a_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('a_updatetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'art',
                'ordering': ['-a_createtime'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255, verbose_name='文章标签名')),
                ('t_info', models.CharField(max_length=50, verbose_name='标签简介')),
                ('t_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['-t_createtime'],
            },
        ),
        migrations.AddField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag'),
        ),
    ]
