# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180505_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='a_content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_createtime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_info',
            field=models.CharField(max_length=300, verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag', verbose_name='关联标签'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_title',
            field=models.CharField(max_length=255, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_updatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_createtime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
