# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180505_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
