# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-a_createtime'], 'verbose_name': '文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-t_createtime'], 'verbose_name': '标签'},
        ),
    ]
