# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180508_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-a_createtime'], 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-t_createtime'], 'verbose_name_plural': '标签'},
        ),
    ]
