# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180509_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='a_img',
            field=models.ImageField(blank=True, null=True, upload_to='arts_ups/%Y/%m', verbose_name='封面'),
        ),
    ]
