# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 20:47
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20180708_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=80, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间')),
                ('flag', models.IntegerField(choices=[(0, '默认'), (1, '待删除'), (2, '已删除')], default=0, verbose_name='控制字段')),
            ],
            options={
                'verbose_name_plural': '会员信息',
                'db_table': 'arts_user',
                'ordering': ['-createtime'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='章节标题')),
                ('content', models.TextField(verbose_name='小说章节内容')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '小说章节',
                'db_table': 'art_chapter',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True, verbose_name='订单号')),
                ('pay_type', models.IntegerField(choices=[(0, '货到付款'), (1, '微信支付'), (2, '支付宝支付')], default=0, verbose_name='控制字段')),
                ('address', models.CharField(default='', max_length=100, verbose_name='订单配送地址')),
                ('phone', models.IntegerField(default=0, verbose_name='订单配送电话')),
                ('order_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下单时间')),
            ],
            options={
                'verbose_name_plural': '用户订单',
                'db_table': 'product_order',
            },
        ),
        migrations.AlterField(
            model_name='art',
            name='a_content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章内容'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Art', verbose_name='小说'),
        ),
    ]
