# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app01', '0009_auto_20180710_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加购物车时间')),
                ('flag', models.IntegerField(choices=[(0, '待下单'), (1, '已下单')], default=0, verbose_name='控制字段')),
            ],
            options={
                'verbose_name_plural': '商品条目',
                'db_table': 'line_item',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='a_flag',
            field=models.IntegerField(choices=[(0, '普通会员'), (1, '白银会员'), (2, '黄金会员')], default=0, verbose_name='控制字段'),
        ),
        migrations.AddField(
            model_name='art',
            name='a_price',
            field=models.IntegerField(default=0, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='art',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='api操作者'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Art', verbose_name='文章商品'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.ProductOrder', to_field='order_id', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ArtsUser', verbose_name='购买者'),
        ),
    ]
