# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20180710_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='t_flag',
            field=models.IntegerField(choices=[(0, '普通会员'), (1, '白银会员'), (2, '黄金会员')], default=0, verbose_name='控制字段'),
        ),
    ]
