# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20180710_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='a_flag',
            field=models.IntegerField(choices=[(0, '普通会员'), (1, '白银会员'), (2, '黄金会员')], default=0, verbose_name='控制字段'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_price',
            field=models.IntegerField(default=0, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag', verbose_name='关联标签'),
        ),
        migrations.AlterField(
            model_name='art',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='api操作者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_flag',
            field=models.IntegerField(choices=[(0, '普通会员'), (1, '白银会员'), (2, '黄金会员')], default=0, verbose_name='控制字段'),
        ),
    ]
