# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_artsuser_telephonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsuser',
            name='telephonenum',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
