# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20180711_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsuser',
            name='telephonenum',
            field=models.CharField(max_length=13, unique=True, verbose_name='手机号码'),
        ),
    ]
