# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_artsuser_telephon_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsuser',
            name='telephon_check',
            field=models.CharField(max_length=20, verbose_name='短信验证码'),
        ),
    ]
