# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20180711_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsuser',
            name='telephon_check',
            field=models.CharField(max_length=20, null=True, verbose_name='短信验证码'),
        ),
    ]
