# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20180711_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品条目和订单关联表',
                'verbose_name_plural': '商品条目和订单关联表',
                'db_table': 'order_item_relation',
            },
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='product_order',
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='flag',
            field=models.IntegerField(choices=[(0, '待下单'), (1, '已下单')], default=0, verbose_name='购买状态'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_id',
            field=models.BigIntegerField(unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '货到付款'), (1, '微信支付'), (2, '支付宝支付')], default=0, verbose_name='支付类型'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='phone',
            field=models.BigIntegerField(default=0, verbose_name='订单配送电话'),
        ),
        migrations.AddField(
            model_name='orderitemrelation',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.LineItem', verbose_name='条目信息'),
        ),
        migrations.AddField(
            model_name='orderitemrelation',
            name='product_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ProductOrder', verbose_name='订单信息'),
        ),
    ]
